name: hamzah_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  get_cli: ^1.8.4
  loading_animation_widget: ^1.2.0+4
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  animate_do: ^3.3.3
  water_drop_nav_bar: ^2.2.0+5
  icons_plus: ^5.0.0
  cached_network_image: ^3.3.1
  sizer: ^2.0.15
  currency_text_input_formatter: ^2.1.10
  popover: ^0.2.8
  uuid: ^3.0.7
  intl: ^0.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/bottom_nav/
    - assets/images/login/
    - assets/images/splashscreen/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    - family: montserratnormal
      fonts:
        - asset: assets/fonts/montserrat-normal.ttf
  uses-material-design: true
